In [1]:
import torch

## Basic operations

In [5]:
a = torch.tensor([1, 2, 3, 4])
b = a * 2

b

tensor([2, 4, 6, 8])

In [6]:
a + b

tensor([ 3,  6,  9, 12])

In [9]:
a + torch.tensor([1.1, 1.2, 1.3, 1.4])

tensor([2.1000, 3.2000, 4.3000, 5.4000])

In [11]:
torch.linspace(-10, 10, steps=8)

tensor([-10.0000,  -7.1429,  -4.2857,  -1.4286,   1.4286,   4.2857,   7.1429,
         10.0000])

## Derivatives

In [9]:
x = torch.tensor(2.0, requires_grad=True)

y = x ** 2

x

tensor(2., requires_grad=True)

In [10]:
y

tensor(4., grad_fn=<PowBackward0>)

$$
f'(x^2) = 2x
$$

In this scenario, $x = 2$, so $f'(2^2) =  2 \cdot (2) = 4$


In [11]:
y.backward()

x.grad

tensor(4.)

In [13]:
x

tensor(2., requires_grad=True)

In [15]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2

print(x.grad)

None
