# Creating torch transformations
----

## Dataset

In [1]:
import torch
from torch.utils.data import Dataset
torch.manual_seed(1)

In [2]:
class ToySet(Dataset):

    def __init__(self, length=100, transform=None):
        self.len = length
        self.x = 2 * torch.ones(length, 2)
        self.y = torch.ones(length, 1)
        self.transform = transform

    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)     
        return sample

    def __len__(self):
        return self.len

In [3]:
# Create Dataset Object. Find out the value on index 1. Find out the length of Dataset Object.

toy_ds = ToySet()
print("Our toy_set object: ", toy_ds)
print("Value on index 0 of our toy_set object: ", toy_ds[0])
print("Our toy_set length: ", len(toy_ds))

Our toy_set object:  <__main__.ToySet object at 0x7f5e5383f910>
Value on index 0 of our toy_set object:  (tensor([2., 2.]), tensor([1.]))
Our toy_set length:  100


The dataset object is an `Iterable`; as a result, we  apply the loop directly on the dataset object 

In [4]:
for x, y in toy_ds:
    print(' x:', x, 'y:', y)

 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 x: tensor([2., 2.]) y: tensor([1.])
 

## Transforms

In [5]:
class AddAndMultiply:

    def __init__(self, addx=1, muly=2):
        self.addx = addx
        self.muly = muly

    # Executor
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x + self.addx
        y = y * self.muly
        sample = x, y
        return sample

In [8]:
am_transform = AddAndMultiply()
print(toy_ds[0])
am_transform(toy_ds[0])

(tensor([2., 2.]), tensor([1.]))


(tensor([3., 3.]), tensor([2.]))

In [12]:
toy_ds_ = ToySet(transform=AddAndMultiply())

toy_ds_[0]

(tensor([3., 3.]), tensor([2.]))

## Compose

In [15]:
from torchvision import transforms
from torchvision.transforms import Compose

In [14]:
class Mult:

    def __init__(self, mult=100):
        self.mult = mult

    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x * self.mult
        y = y * self.mult
        sample = x, y
        return sample

In [16]:
transforms = Compose([
    AddAndMultiply(),
    Mult()
])

transforms

Compose(
)

In [18]:
print(toy_ds[0])
transforms(toy_ds[0])

(tensor([2., 2.]), tensor([1.]))


(tensor([300., 300.]), tensor([200.]))

In [20]:
toy_ds_composed = ToySet(transform=transforms)

In [21]:
toy_ds_composed[0]

(tensor([300., 300.]), tensor([200.]))